using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Microsoft.Maui.DevFlow.Agent.SourceGen;

/// <summary>
/// Source generator that auto-injects <c>AddMauiDevFlowAgent()</c> by intercepting
/// <c>MauiAppBuilder.Build()</c> calls. Activated when the consuming project sets
/// <c>&lt;InitMauiDevFlowAgent&gt;true&lt;/InitMauiDevFlowAgent&gt;</c>.
/// </summary>
[Generator]
public sealed class DevFlowAutoInitGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Read MSBuild properties forwarded via CompilerVisibleProperty
        var properties = context.AnalyzerConfigOptionsProvider.Select((provider, _) =>
        {
            provider.GlobalOptions.TryGetValue("build_property.InitMauiDevFlowAgent", out var init);
            provider.GlobalOptions.TryGetValue("build_property.MauiDevFlowPort", out var port);
            provider.GlobalOptions.TryGetValue("build_property.MauiDevFlowFileLogging", out var fileLogging);
            provider.GlobalOptions.TryGetValue("build_property.MauiDevFlowNetworkMonitoring", out var networkMonitoring);
            provider.GlobalOptions.TryGetValue("build_property.MauiDevFlowProfiler", out var profiler);
            return new DevFlowProperties(init, port, fileLogging, networkMonitoring, profiler);
        });

        // Find .Build() invocations that resolve to MauiAppBuilder.Build()
        var buildCalls = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: IsCandidateBuildCall,
            transform: GetBuildCallInfo
        ).Where(static info => info.HasValue).Select(static (info, _) => info!.Value);

        var combined = buildCalls.Collect().Combine(properties);

        context.RegisterSourceOutput(combined, GenerateInterceptor);
    }

    /// <summary>
    /// Fast syntax-only check: is this an argumentless <c>.Build()</c> member-access invocation?
    /// </summary>
    private static bool IsCandidateBuildCall(SyntaxNode node, CancellationToken ct)
    {
        return node is InvocationExpressionSyntax
        {
            Expression: MemberAccessExpressionSyntax { Name.Identifier.ValueText: "Build" },
            ArgumentList.Arguments.Count: 0,
        };
    }

    /// <summary>
    /// Semantic check: does the invocation resolve to <c>MauiAppBuilder.Build()</c>?
    /// If so, capture the source location of the <c>Build</c> name token.
    /// </summary>
    private static BuildCallInfo? GetBuildCallInfo(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var symbolInfo = context.SemanticModel.GetSymbolInfo(invocation, ct);

        if (symbolInfo.Symbol is not IMethodSymbol method)
            return null;
        if (method.ContainingType?.ToDisplayString() != "Microsoft.Maui.Hosting.MauiAppBuilder")
            return null;
        if (method.Name != "Build")
            return null;

        var memberAccess = (MemberAccessExpressionSyntax)invocation.Expression;
        var lineSpan = memberAccess.Name.GetLocation().GetLineSpan();

        return new BuildCallInfo(
            lineSpan.Path,
            lineSpan.StartLinePosition.Line + 1,
            lineSpan.StartLinePosition.Character + 1);
    }

    /// <summary>
    /// Emit the interceptor source when <c>InitMauiDevFlowAgent</c> is <c>true</c>.
    /// </summary>
    private static void GenerateInterceptor(
        SourceProductionContext context,
        (ImmutableArray<BuildCallInfo> Calls, DevFlowProperties Props) source)
    {
        var (calls, props) = source;

        if (!string.Equals(props.InitEnabled, "true", StringComparison.OrdinalIgnoreCase))
            return;

        if (calls.IsDefaultOrEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS9113 // Parameter is unread");
        sb.AppendLine();

        // Define InterceptsLocationAttribute as file-scoped to avoid conflicts
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(string filePath, int line, int character) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("#pragma warning restore CS9113");
        sb.AppendLine();

        sb.AppendLine("namespace Microsoft.Maui.DevFlow.Agent.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    file static class DevFlowAutoInit");
        sb.AppendLine("    {");

        // Emit an [InterceptsLocation] for every MauiAppBuilder.Build() call site
        foreach (var call in calls)
        {
            // Use verbatim string — only escape double quotes
            var escaped = call.FilePath.Replace("\"", "\"\"");
            sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation(@\"{escaped}\", {call.Line}, {call.Column})]");
        }

        sb.AppendLine("        internal static global::Microsoft.Maui.Hosting.MauiApp DevFlowBuild(");
        sb.AppendLine("            this global::Microsoft.Maui.Hosting.MauiAppBuilder builder)");
        sb.AppendLine("        {");
        sb.AppendLine("            // Guard: skip if the user already registered DevFlow explicitly");
        sb.AppendLine("            bool alreadyRegistered = false;");
        sb.AppendLine("            foreach (var sd in builder.Services)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (sd.ServiceType == typeof(global::Microsoft.Maui.DevFlow.Agent.Core.DevFlowAgentService))");
        sb.AppendLine("                {");
        sb.AppendLine("                    alreadyRegistered = true;");
        sb.AppendLine("                    break;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            if (!alreadyRegistered)");
        sb.AppendLine("            {");

        // Generate AddMauiDevFlowAgent call with options from MSBuild properties
        var hasOptions = HasAnyOption(props);
        if (hasOptions)
        {
            sb.AppendLine("                global::Microsoft.Maui.DevFlow.Agent.AgentServiceExtensions.AddMauiDevFlowAgent(builder, options =>");
            sb.AppendLine("                {");
            if (!string.IsNullOrEmpty(props.Port) && int.TryParse(props.Port, out var port))
                sb.AppendLine($"                    options.Port = {port};");
            if (IsBoolProperty(props.FileLogging, out var fl))
                sb.AppendLine($"                    options.EnableFileLogging = {BoolLiteral(fl)};");
            if (IsBoolProperty(props.NetworkMonitoring, out var nm))
                sb.AppendLine($"                    options.EnableNetworkMonitoring = {BoolLiteral(nm)};");
            if (IsBoolProperty(props.Profiler, out var pr))
                sb.AppendLine($"                    options.EnableProfiler = {BoolLiteral(pr)};");
            sb.AppendLine("                });");
        }
        else
        {
            sb.AppendLine("                global::Microsoft.Maui.DevFlow.Agent.AgentServiceExtensions.AddMauiDevFlowAgent(builder);");
        }

        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return builder.Build();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("DevFlowAutoInit.g.cs", sb.ToString());
    }

    private static bool HasAnyOption(DevFlowProperties props) =>
        (!string.IsNullOrEmpty(props.Port) && int.TryParse(props.Port, out _)) ||
        IsBoolProperty(props.FileLogging, out _) ||
        IsBoolProperty(props.NetworkMonitoring, out _) ||
        IsBoolProperty(props.Profiler, out _);

    private static bool IsBoolProperty(string? value, out bool result)
    {
        if (string.Equals(value, "true", StringComparison.OrdinalIgnoreCase))
        {
            result = true;
            return true;
        }
        if (string.Equals(value, "false", StringComparison.OrdinalIgnoreCase))
        {
            result = false;
            return true;
        }
        result = false;
        return false;
    }

    private static string BoolLiteral(bool value) => value ? "true" : "false";
}

/// <summary>Source location of a <c>MauiAppBuilder.Build()</c> call site.</summary>
internal readonly struct BuildCallInfo : IEquatable<BuildCallInfo>
{
    public readonly string FilePath;
    public readonly int Line;
    public readonly int Column;

    public BuildCallInfo(string filePath, int line, int column)
    {
        FilePath = filePath;
        Line = line;
        Column = column;
    }

    public bool Equals(BuildCallInfo other) =>
        FilePath == other.FilePath && Line == other.Line && Column == other.Column;

    public override bool Equals(object? obj) => obj is BuildCallInfo other && Equals(other);

    public override int GetHashCode()
    {
        unchecked
        {
            var hash = 17;
            hash = hash * 31 + (FilePath != null ? FilePath.GetHashCode() : 0);
            hash = hash * 31 + Line;
            hash = hash * 31 + Column;
            return hash;
        }
    }
}

/// <summary>MSBuild properties forwarded to the generator via <c>CompilerVisibleProperty</c>.</summary>
internal readonly struct DevFlowProperties : IEquatable<DevFlowProperties>
{
    public readonly string? InitEnabled;
    public readonly string? Port;
    public readonly string? FileLogging;
    public readonly string? NetworkMonitoring;
    public readonly string? Profiler;

    public DevFlowProperties(string? initEnabled, string? port, string? fileLogging,
                             string? networkMonitoring, string? profiler)
    {
        InitEnabled = initEnabled;
        Port = port;
        FileLogging = fileLogging;
        NetworkMonitoring = networkMonitoring;
        Profiler = profiler;
    }

    public bool Equals(DevFlowProperties other) =>
        InitEnabled == other.InitEnabled &&
        Port == other.Port &&
        FileLogging == other.FileLogging &&
        NetworkMonitoring == other.NetworkMonitoring &&
        Profiler == other.Profiler;

    public override bool Equals(object? obj) => obj is DevFlowProperties other && Equals(other);

    public override int GetHashCode()
    {
        unchecked
        {
            var hash = 17;
            hash = hash * 31 + (InitEnabled != null ? InitEnabled.GetHashCode() : 0);
            hash = hash * 31 + (Port != null ? Port.GetHashCode() : 0);
            hash = hash * 31 + (FileLogging != null ? FileLogging.GetHashCode() : 0);
            hash = hash * 31 + (NetworkMonitoring != null ? NetworkMonitoring.GetHashCode() : 0);
            hash = hash * 31 + (Profiler != null ? Profiler.GetHashCode() : 0);
            return hash;
        }
    }
}
