//HintName: ToolsCtx.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS8019 // Unnecessary using directive
#pragma warning disable CS8604 // Possible null reference argument (JSON-deserialized values passed to non-nullable parameters)
#pragma warning disable CS1998 // Async method lacks 'await' operators (sync property getters/void tools are emitted as async)

using global::System;
using global::System.Collections.Generic;
using global::System.Reflection;
using global::System.Text.Json;
using global::System.Threading;
using global::System.Threading.Tasks;
using global::Microsoft.Extensions.AI;
using global::Microsoft.Extensions.DependencyInjection;

namespace Sample
{
    public partial class ToolsCtx
    {
        /// <summary>Gets the default singleton instance of this tool context.</summary>
        public static ToolsCtx Default { get; } = new ToolsCtx();

        private static readonly global::Microsoft.Extensions.AI.AITool[] s_tools = new global::Microsoft.Extensions.AI.AITool[]
        {
            new DisplaySettings_Mode_Get_Tool(),
            new DisplaySettings_Mode_Set_Tool(),
        };

        /// <inheritdoc />
        public override global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Extensions.AI.AITool> Tools => s_tools;

        private sealed class DisplaySettings_Mode_Get_Tool : global::Microsoft.Extensions.AI.AIFunction
        {
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

            public override string Name => "get_display_mode";
            public override string Description => "Gets the current display mode.";
            public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
            public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

            private static global::System.Reflection.MethodInfo GetTargetMethod()
            {
                var serviceType = typeof(global::Sample.DisplaySettings);
                var prop = serviceType.GetProperty("Mode", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance)
                    ?? throw new global::System.InvalidOperationException("Could not locate target property global::Sample.DisplaySettings.Mode.");
                return prop.GetMethod
                    ?? throw new global::System.InvalidOperationException("Property global::Sample.DisplaySettings.Mode has no getter.");
            }

            private static readonly global::System.Collections.Generic.HashSet<string> s_schemaExcludedParameters = new()
            {
            };

            private static global::System.Text.Json.JsonElement BuildSchema()
            {
                var inferenceOptions = new global::Microsoft.Extensions.AI.AIJsonSchemaCreateOptions
                {
                    IncludeParameter = static p => !s_schemaExcludedParameters.Contains(p.Name!),
                };
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateFunctionJsonSchema(
                    GetTargetMethod(), title: string.Empty, description: string.Empty, inferenceOptions: inferenceOptions);
            }

            private static global::System.Text.Json.JsonElement? BuildReturnSchema()
            {
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(string));
            }

            protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
                global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
                global::System.Threading.CancellationToken cancellationToken)
            {
                var __provider = arguments.Services ?? throw new global::System.InvalidOperationException(
                    "Tool 'get_display_mode' requires services (source type: global::Sample.DisplaySettings) but no IServiceProvider was supplied. " +
                    "Set AIFunctionArguments.Services before invoking the tool (ChatClientBuilder.UseFunctionInvocation().Build(sp) does this automatically).");
                var __service = __provider.GetService<global::Sample.DisplaySettings>() ?? throw new global::System.InvalidOperationException(
                    "Tool 'get_display_mode' could not resolve its source type 'global::Sample.DisplaySettings' from IServiceProvider. " +
                    "Register the service in your DI container, or use ChatClientBuilder.UseFunctionInvocation().Build(sp) to supply a configured IServiceProvider.");
                var __result = __service.Mode;
                return __result;
            }
        }

        private sealed class DisplaySettings_Mode_Set_Tool : global::Microsoft.Extensions.AI.AIFunction
        {
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

            public override string Name => "set_display_mode";
            public override string Description => "Sets the display mode.";
            public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
            public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

            private static global::System.Reflection.MethodInfo GetTargetMethod()
            {
                var serviceType = typeof(global::Sample.DisplaySettings);
                var prop = serviceType.GetProperty("Mode", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance)
                    ?? throw new global::System.InvalidOperationException("Could not locate target property global::Sample.DisplaySettings.Mode.");
                return prop.SetMethod
                    ?? throw new global::System.InvalidOperationException("Property global::Sample.DisplaySettings.Mode has no setter.");
            }

            private static readonly global::System.Collections.Generic.HashSet<string> s_schemaExcludedParameters = new()
            {
            };

            private static global::System.Text.Json.JsonElement BuildSchema()
            {
                var inferenceOptions = new global::Microsoft.Extensions.AI.AIJsonSchemaCreateOptions
                {
                    IncludeParameter = static p => !s_schemaExcludedParameters.Contains(p.Name!),
                };
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateFunctionJsonSchema(
                    GetTargetMethod(), title: string.Empty, description: string.Empty, inferenceOptions: inferenceOptions);
            }

            private static global::System.Text.Json.JsonElement? BuildReturnSchema()
            {
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(string));
            }

            protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
                global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
                global::System.Threading.CancellationToken cancellationToken)
            {
                var __provider = arguments.Services ?? throw new global::System.InvalidOperationException(
                    "Tool 'set_display_mode' requires services (source type: global::Sample.DisplaySettings) but no IServiceProvider was supplied. " +
                    "Set AIFunctionArguments.Services before invoking the tool (ChatClientBuilder.UseFunctionInvocation().Build(sp) does this automatically).");
                var __service = __provider.GetService<global::Sample.DisplaySettings>() ?? throw new global::System.InvalidOperationException(
                    "Tool 'set_display_mode' could not resolve its source type 'global::Sample.DisplaySettings' from IServiceProvider. " +
                    "Register the service in your DI container, or use ChatClientBuilder.UseFunctionInvocation().Build(sp) to supply a configured IServiceProvider.");
                var __arg_value = global::Microsoft.Maui.AI.Attributes.AIToolMetadataServices.GetRequiredArg<string>(arguments, "value");
                var __result = (__service.Mode = __arg_value);
                return __result;
            }
        }

    }
}
