//HintName: DataTools.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS8019 // Unnecessary using directive
#pragma warning disable CS8604 // Possible null reference argument (JSON-deserialized values passed to non-nullable parameters)
#pragma warning disable CS1998 // Async method lacks 'await' operators (sync property getters/void tools are emitted as async)

using global::System;
using global::System.Collections.Generic;
using global::System.Reflection;
using global::System.Text.Json;
using global::System.Threading;
using global::System.Threading.Tasks;
using global::Microsoft.Extensions.AI;
using global::Microsoft.Extensions.DependencyInjection;

namespace Sample
{
    public partial class DataTools
    {
        /// <summary>Gets the default singleton instance of this tool context.</summary>
        public static DataTools Default { get; } = new DataTools();

        private static readonly global::Microsoft.Extensions.AI.AITool[] s_tools = new global::Microsoft.Extensions.AI.AITool[]
        {
            new DataAccess_Query_Tool(),
            new DataAccess_Records_Get_Tool(),
        };

        /// <inheritdoc />
        public override global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Extensions.AI.AITool> Tools => s_tools;

        private sealed class DataAccess_Query_Tool : global::Microsoft.Extensions.AI.AIFunction
        {
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

            public override string Name => "query_records";
            public override string Description => "Queries records.";
            public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
            public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

            private static global::System.Reflection.MethodInfo GetTargetMethod()
            {
                var serviceType = typeof(global::Sample.DataAccess);
                var paramTypes = new global::System.Type[] { typeof(string), typeof(global::Sample.IDb), };
                return serviceType.GetMethod("Query", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static, null, paramTypes, null)
                    ?? throw new global::System.InvalidOperationException("Could not locate target method global::Sample.DataAccess.Query.");
            }

            private static readonly global::System.Collections.Generic.HashSet<string> s_schemaExcludedParameters = new()
            {
                "db",
            };

            private static global::System.Text.Json.JsonElement BuildSchema()
            {
                var inferenceOptions = new global::Microsoft.Extensions.AI.AIJsonSchemaCreateOptions
                {
                    IncludeParameter = static p => !s_schemaExcludedParameters.Contains(p.Name!),
                };
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateFunctionJsonSchema(
                    GetTargetMethod(), title: string.Empty, description: string.Empty, inferenceOptions: inferenceOptions);
            }

            private static global::System.Text.Json.JsonElement? BuildReturnSchema()
            {
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(string));
            }

            protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
                global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
                global::System.Threading.CancellationToken cancellationToken)
            {
                var __provider = arguments.Services ?? throw new global::System.InvalidOperationException(
                    "Tool 'query_records' requires services (source type: global::Sample.DataAccess) but no IServiceProvider was supplied. " +
                    "Set AIFunctionArguments.Services before invoking the tool (ChatClientBuilder.UseFunctionInvocation().Build(sp) does this automatically).");
                var __arg_filter = global::Microsoft.Maui.AI.Attributes.AIToolMetadataServices.GetRequiredArg<string>(arguments, "filter");
                var __arg_db = __provider.GetService<global::Sample.IDb>() ?? throw new global::System.InvalidOperationException(
                    "Tool parameter 'db' of type 'global::Sample.IDb' could not be resolved from IServiceProvider. " +
                    "Register the service in your DI container.");
                var __result = global::Sample.DataAccess.Query(__arg_filter, __arg_db);
                return __result;
            }
        }

        private sealed class DataAccess_Records_Get_Tool : global::Microsoft.Extensions.AI.AIFunction
        {
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

            public override string Name => "all_records";
            public override string Description => "All records.";
            public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
            public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

            private static global::System.Reflection.MethodInfo GetTargetMethod()
            {
                var serviceType = typeof(global::Sample.DataAccess);
                var prop = serviceType.GetProperty("Records", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static)
                    ?? throw new global::System.InvalidOperationException("Could not locate target property global::Sample.DataAccess.Records.");
                return prop.GetMethod
                    ?? throw new global::System.InvalidOperationException("Property global::Sample.DataAccess.Records has no getter.");
            }

            private static readonly global::System.Collections.Generic.HashSet<string> s_schemaExcludedParameters = new()
            {
            };

            private static global::System.Text.Json.JsonElement BuildSchema()
            {
                var inferenceOptions = new global::Microsoft.Extensions.AI.AIJsonSchemaCreateOptions
                {
                    IncludeParameter = static p => !s_schemaExcludedParameters.Contains(p.Name!),
                };
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateFunctionJsonSchema(
                    GetTargetMethod(), title: string.Empty, description: string.Empty, inferenceOptions: inferenceOptions);
            }

            private static global::System.Text.Json.JsonElement? BuildReturnSchema()
            {
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(global::System.Collections.Generic.IReadOnlyList<string>));
            }

            protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
                global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
                global::System.Threading.CancellationToken cancellationToken)
            {
                var __result = global::Sample.DataAccess.Records;
                return __result;
            }
        }

    }
}
