//HintName: ToolsCtx.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS8019 // Unnecessary using directive
#pragma warning disable CS8604 // Possible null reference argument (JSON-deserialized values passed to non-nullable parameters)
#pragma warning disable CS1998 // Async method lacks 'await' operators (sync property getters/void tools are emitted as async)

using global::System;
using global::System.Collections.Generic;
using global::System.Reflection;
using global::System.Text.Json;
using global::System.Threading;
using global::System.Threading.Tasks;
using global::Microsoft.Extensions.AI;
using global::Microsoft.Extensions.DependencyInjection;

public partial class ToolsCtx
{
    /// <summary>Gets the default singleton instance of this tool context.</summary>
    public static ToolsCtx Default { get; } = new ToolsCtx();

    private static readonly global::Microsoft.Extensions.AI.AITool[] s_tools = new global::Microsoft.Extensions.AI.AITool[]
    {
        new Svc_Do_Tool(),
    };

    /// <inheritdoc />
    public override global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Extensions.AI.AITool> Tools => s_tools;

    private sealed class Svc_Do_Tool : global::Microsoft.Extensions.AI.AIFunction
    {
        private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
        private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

        public override string Name => "Do";
        public override string Description => string.Empty;
        public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
        public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

        private static global::System.Reflection.MethodInfo GetTargetMethod()
        {
            var serviceType = typeof(global::Svc);
            var paramTypes = new global::System.Type[] { typeof(string), };
            return serviceType.GetMethod("Do", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, paramTypes, null)
                ?? throw new global::System.InvalidOperationException("Could not locate target method global::Svc.Do.");
        }

        private static readonly global::System.Collections.Generic.HashSet<string> s_schemaExcludedParameters = new()
        {
        };

        private static global::System.Text.Json.JsonElement BuildSchema()
        {
            var inferenceOptions = new global::Microsoft.Extensions.AI.AIJsonSchemaCreateOptions
            {
                IncludeParameter = static p => !s_schemaExcludedParameters.Contains(p.Name!),
            };
            return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateFunctionJsonSchema(
                GetTargetMethod(), title: string.Empty, description: string.Empty, inferenceOptions: inferenceOptions);
        }

        private static global::System.Text.Json.JsonElement? BuildReturnSchema()
        {
            return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(string));
        }

        protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
            global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
            global::System.Threading.CancellationToken cancellationToken)
        {
            var __provider = arguments.Services ?? throw new global::System.InvalidOperationException(
                "Tool 'Do' requires services (source type: global::Svc) but no IServiceProvider was supplied. " +
                "Set AIFunctionArguments.Services before invoking the tool (ChatClientBuilder.UseFunctionInvocation().Build(sp) does this automatically).");
            var __service = __provider.GetService<global::Svc>() ?? throw new global::System.InvalidOperationException(
                "Tool 'Do' could not resolve its source type 'global::Svc' from IServiceProvider. " +
                "Register the service in your DI container, or use ChatClientBuilder.UseFunctionInvocation().Build(sp) to supply a configured IServiceProvider.");
            var __arg_x = global::Microsoft.Maui.AI.Attributes.AIToolMetadataServices.GetRequiredArg<string>(arguments, "x");
            var __result = __service.Do(__arg_x);
            return __result;
        }
    }

}
