// <auto-generated/>
#nullable enable
using System;

namespace Microsoft.Maui.Labs.HotReload
{
	/// <summary>
	/// Implemented by types that want to be notified when their code is updated via .NET Hot Reload.
	/// </summary>
	/// <remarks>
	/// To register for notifications, call <c>HotReloadInitialize()</c> in your constructor
	/// (generated automatically by <c>Microsoft.Maui.Labs.HotReload.SourceGen</c> for <c>partial</c> classes).
	/// </remarks>
	public interface IHotReloadAware
	{
		/// <summary>
		/// Called when this instance's type (or a base type) has been updated via hot reload.
		/// </summary>
		/// <param name="updatedTypes">
		/// The set of types that were updated, as reported by the .NET Hot Reload host.
		/// May be <see langword="null"/> if the host did not provide type information.
		/// </param>
		void OnHotReload(Type[]? updatedTypes);
	}
}
