// <auto-generated/>
#nullable enable
namespace Microsoft.Maui.HotReload
{
	/// <summary>
	/// Implemented by types that want to be notified when their code is updated via .NET Hot Reload.
	/// </summary>
	/// <remarks>
	/// To register for notifications, call <c>HotReloadInitialize()</c> in your constructor
	/// (generated automatically by <c>Microsoft.Maui.HotReload.SourceGen</c> for <c>partial</c> classes).
	/// </remarks>
	public interface IHotReloadable
	{
		/// <summary>Called when this instance's type (or a base type) has been updated via hot reload.</summary>
		void OnHotReload();
	}
}
