//HintName: ToolsCtx.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS8019 // Unnecessary using directive
#pragma warning disable CS8604 // Possible null reference argument (JSON-deserialized values passed to non-nullable parameters)
#pragma warning disable CS1998 // Async method lacks 'await' operators (sync property getters/void tools are emitted as async)

using global::System;
using global::System.Collections.Generic;
using global::System.Text.Json;
using global::System.Threading;
using global::System.Threading.Tasks;
using global::Microsoft.Extensions.AI;
using global::Microsoft.Extensions.DependencyInjection;

namespace Sample
{
    public partial class ToolsCtx
    {
        /// <summary>Gets the default singleton instance of this tool context.</summary>
        public static ToolsCtx Default { get; } = new ToolsCtx();

        private static readonly global::System.Text.Json.JsonSerializerOptions s_jsonOptions = global::Microsoft.Extensions.AI.AIJsonUtilities.DefaultOptions;

        private static readonly global::Microsoft.Extensions.AI.AITool[] s_tools = new global::Microsoft.Extensions.AI.AITool[]
        {
            new Svc_Add_Tool(),
        };

        /// <inheritdoc />
        public override global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Extensions.AI.AITool> Tools => s_tools;

        private sealed class Svc_Add_Tool : global::Microsoft.Extensions.AI.AIFunction
        {
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

            public override string Name => "Add";
            public override string Description => "Adds two numbers and returns the sum.";
            public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
            public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

            private static global::System.Text.Json.JsonElement BuildSchema()
            {
                var properties = new global::System.Text.Json.Nodes.JsonObject();
                var required = new global::System.Text.Json.Nodes.JsonArray();
                properties["a"] = global::System.Text.Json.Nodes.JsonNode.Parse(global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(int), serializerOptions: s_jsonOptions).GetRawText());
                if (properties["a"] is global::System.Text.Json.Nodes.JsonObject aObj)
                    aObj["description"] = "First addend";
                required.Add("a");
                properties["b"] = global::System.Text.Json.Nodes.JsonNode.Parse(global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(int), serializerOptions: s_jsonOptions).GetRawText());
                if (properties["b"] is global::System.Text.Json.Nodes.JsonObject bObj)
                    bObj["description"] = "Second addend";
                required.Add("b");
                var schema = new global::System.Text.Json.Nodes.JsonObject
                {
                    ["type"] = "object",
                    ["properties"] = properties,
                };
                if (required.Count > 0)
                    schema["required"] = required;
                schema["additionalProperties"] = false;
                return global::System.Text.Json.JsonSerializer.SerializeToElement(schema);
            }

            private static global::System.Text.Json.JsonElement? BuildReturnSchema()
            {
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(int), serializerOptions: s_jsonOptions);
            }

            protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
                global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
                global::System.Threading.CancellationToken cancellationToken)
            {
                var __provider = arguments.Services ?? throw new global::System.InvalidOperationException(
                    "Tool 'Add' requires services (source type: global::Sample.Svc) but no IServiceProvider was supplied. " +
                    "Set AIFunctionArguments.Services before invoking the tool (ChatClientBuilder.UseFunctionInvocation().Build(sp) does this automatically).");
                var __service = __provider.GetService<global::Sample.Svc>() ?? throw new global::System.InvalidOperationException(
                    "Tool 'Add' could not resolve its source type 'global::Sample.Svc' from IServiceProvider. " +
                    "Register the service in your DI container, or use ChatClientBuilder.UseFunctionInvocation().Build(sp) to supply a configured IServiceProvider.");
                var __arg_a = global::Microsoft.Maui.AI.Attributes.AIToolMetadataServices.GetRequiredArg<int>(arguments, "a", (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<int>)s_jsonOptions.GetTypeInfo(typeof(int)));
                var __arg_b = global::Microsoft.Maui.AI.Attributes.AIToolMetadataServices.GetRequiredArg<int>(arguments, "b", (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<int>)s_jsonOptions.GetTypeInfo(typeof(int)));
                var __result = __service.Add(__arg_a, __arg_b);
                return __result;
            }
        }

    }
}
