//HintName: MauiAIAttributesGeneratorTestsToolContext.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS8019 // Unnecessary using directive
#pragma warning disable CS8604 // Possible null reference argument (JSON-deserialized values passed to non-nullable parameters)
#pragma warning disable CS1998 // Async method lacks 'await' operators (sync property getters/void tools are emitted as async)

using global::System;
using global::System.Collections.Generic;
using global::System.Text.Json;
using global::System.Threading;
using global::System.Threading.Tasks;
using global::Microsoft.Extensions.AI;
using global::Microsoft.Extensions.DependencyInjection;

namespace Sample
{
    internal partial class MauiAIAttributesGeneratorTestsToolContext : global::Microsoft.Maui.AI.Attributes.AIToolContext
    {
        /// <summary>Gets the default singleton instance of this tool context.</summary>
        public static MauiAIAttributesGeneratorTestsToolContext Default { get; } = new MauiAIAttributesGeneratorTestsToolContext();

        private static readonly global::System.Text.Json.JsonSerializerOptions s_jsonOptions = global::Microsoft.Extensions.AI.AIJsonUtilities.DefaultOptions;

        private static readonly global::Microsoft.Extensions.AI.AITool[] s_tools = new global::Microsoft.Extensions.AI.AITool[]
        {
            new SvcA_DoA_Tool(),
            new SvcB_DoB_Tool(),
        };

        /// <inheritdoc />
        public override global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Extensions.AI.AITool> Tools => s_tools;

        private sealed class SvcA_DoA_Tool : global::Microsoft.Extensions.AI.AIFunction
        {
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

            public override string Name => "DoA";
            public override string Description => string.Empty;
            public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
            public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

            private static global::System.Text.Json.JsonElement BuildSchema()
            {
                var properties = new global::System.Text.Json.Nodes.JsonObject();
                var required = new global::System.Text.Json.Nodes.JsonArray();
                properties["x"] = global::System.Text.Json.Nodes.JsonNode.Parse(global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(string), serializerOptions: s_jsonOptions).GetRawText());
                required.Add("x");
                var schema = new global::System.Text.Json.Nodes.JsonObject
                {
                    ["type"] = "object",
                    ["properties"] = properties,
                };
                if (required.Count > 0)
                    schema["required"] = required;
                schema["additionalProperties"] = false;
                return global::System.Text.Json.JsonSerializer.SerializeToElement(schema);
            }

            private static global::System.Text.Json.JsonElement? BuildReturnSchema()
            {
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(string), serializerOptions: s_jsonOptions);
            }

            protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
                global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
                global::System.Threading.CancellationToken cancellationToken)
            {
                var __provider = arguments.Services ?? throw new global::System.InvalidOperationException(
                    "Tool 'DoA' requires services (source type: global::Sample.SvcA) but no IServiceProvider was supplied. " +
                    "Set AIFunctionArguments.Services before invoking the tool (ChatClientBuilder.UseFunctionInvocation().Build(sp) does this automatically).");
                var __service = __provider.GetService<global::Sample.SvcA>() ?? throw new global::System.InvalidOperationException(
                    "Tool 'DoA' could not resolve its source type 'global::Sample.SvcA' from IServiceProvider. " +
                    "Register the service in your DI container, or use ChatClientBuilder.UseFunctionInvocation().Build(sp) to supply a configured IServiceProvider.");
                var __arg_x = global::Microsoft.Maui.AI.Attributes.AIToolMetadataServices.GetRequiredArg<string>(arguments, "x", (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)s_jsonOptions.GetTypeInfo(typeof(string)));
                var __result = __service.DoA(__arg_x);
                return __result;
            }
        }

        private sealed class SvcB_DoB_Tool : global::Microsoft.Extensions.AI.AIFunction
        {
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

            public override string Name => "DoB";
            public override string Description => string.Empty;
            public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
            public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

            private static global::System.Text.Json.JsonElement BuildSchema()
            {
                var properties = new global::System.Text.Json.Nodes.JsonObject();
                var required = new global::System.Text.Json.Nodes.JsonArray();
                properties["x"] = global::System.Text.Json.Nodes.JsonNode.Parse(global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(string), serializerOptions: s_jsonOptions).GetRawText());
                required.Add("x");
                var schema = new global::System.Text.Json.Nodes.JsonObject
                {
                    ["type"] = "object",
                    ["properties"] = properties,
                };
                if (required.Count > 0)
                    schema["required"] = required;
                schema["additionalProperties"] = false;
                return global::System.Text.Json.JsonSerializer.SerializeToElement(schema);
            }

            private static global::System.Text.Json.JsonElement? BuildReturnSchema()
            {
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(string), serializerOptions: s_jsonOptions);
            }

            protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
                global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
                global::System.Threading.CancellationToken cancellationToken)
            {
                var __provider = arguments.Services ?? throw new global::System.InvalidOperationException(
                    "Tool 'DoB' requires services (source type: global::Sample.SvcB) but no IServiceProvider was supplied. " +
                    "Set AIFunctionArguments.Services before invoking the tool (ChatClientBuilder.UseFunctionInvocation().Build(sp) does this automatically).");
                var __service = __provider.GetService<global::Sample.SvcB>() ?? throw new global::System.InvalidOperationException(
                    "Tool 'DoB' could not resolve its source type 'global::Sample.SvcB' from IServiceProvider. " +
                    "Register the service in your DI container, or use ChatClientBuilder.UseFunctionInvocation().Build(sp) to supply a configured IServiceProvider.");
                var __arg_x = global::Microsoft.Maui.AI.Attributes.AIToolMetadataServices.GetRequiredArg<string>(arguments, "x", (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)s_jsonOptions.GetTypeInfo(typeof(string)));
                var __result = __service.DoB(__arg_x);
                return __result;
            }
        }

    }
}
