//HintName: DangerousTools.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS8019 // Unnecessary using directive
#pragma warning disable CS8604 // Possible null reference argument (JSON-deserialized values passed to non-nullable parameters)
#pragma warning disable CS1998 // Async method lacks 'await' operators (sync property getters/void tools are emitted as async)

using global::System;
using global::System.Collections.Generic;
using global::System.Text.Json;
using global::System.Threading;
using global::System.Threading.Tasks;
using global::Microsoft.Extensions.AI;
using global::Microsoft.Extensions.DependencyInjection;

namespace Sample
{
    public partial class DangerousTools
    {
        /// <summary>Gets the default singleton instance of this tool context.</summary>
        public static DangerousTools Default { get; } = new DangerousTools();

        private static readonly global::System.Text.Json.JsonSerializerOptions s_jsonOptions = global::Microsoft.Extensions.AI.AIJsonUtilities.DefaultOptions;

        private static readonly global::Microsoft.Extensions.AI.AITool[] s_tools = new global::Microsoft.Extensions.AI.AITool[]
        {
            new IDangerousService_Read_Tool(),
            new global::Microsoft.Extensions.AI.ApprovalRequiredAIFunction(new IDangerousService_Write_Tool()),
        };

        /// <inheritdoc />
        public override global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Extensions.AI.AITool> Tools => s_tools;

        private sealed class IDangerousService_Read_Tool : global::Microsoft.Extensions.AI.AIFunction
        {
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

            public override string Name => "safe_read";
            public override string Description => "Safe operation.";
            public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
            public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

            private static global::System.Text.Json.JsonElement BuildSchema()
            {
                var properties = new global::System.Text.Json.Nodes.JsonObject();
                var required = new global::System.Text.Json.Nodes.JsonArray();
                var schema = new global::System.Text.Json.Nodes.JsonObject
                {
                    ["type"] = "object",
                    ["properties"] = properties,
                };
                if (required.Count > 0)
                    schema["required"] = required;
                schema["additionalProperties"] = false;
                return global::System.Text.Json.JsonSerializer.SerializeToElement(schema);
            }

            private static global::System.Text.Json.JsonElement? BuildReturnSchema()
            {
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(string), serializerOptions: s_jsonOptions);
            }

            protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
                global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
                global::System.Threading.CancellationToken cancellationToken)
            {
                var __provider = arguments.Services ?? throw new global::System.InvalidOperationException(
                    "Tool 'safe_read' requires services (source type: global::Sample.IDangerousService) but no IServiceProvider was supplied. " +
                    "Set AIFunctionArguments.Services before invoking the tool (ChatClientBuilder.UseFunctionInvocation().Build(sp) does this automatically).");
                var __service = __provider.GetService<global::Sample.IDangerousService>() ?? throw new global::System.InvalidOperationException(
                    "Tool 'safe_read' could not resolve its source type 'global::Sample.IDangerousService' from IServiceProvider. " +
                    "Register the service in your DI container, or use ChatClientBuilder.UseFunctionInvocation().Build(sp) to supply a configured IServiceProvider.");
                var __result = __service.Read();
                return __result;
            }
        }

        private sealed class IDangerousService_Write_Tool : global::Microsoft.Extensions.AI.AIFunction
        {
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

            public override string Name => "dangerous_write";
            public override string Description => "Dangerous write operation.";
            public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
            public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

            private static global::System.Text.Json.JsonElement BuildSchema()
            {
                var properties = new global::System.Text.Json.Nodes.JsonObject();
                var required = new global::System.Text.Json.Nodes.JsonArray();
                properties["data"] = global::System.Text.Json.Nodes.JsonNode.Parse(global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(string), serializerOptions: s_jsonOptions).GetRawText());
                if (properties["data"] is global::System.Text.Json.Nodes.JsonObject dataObj)
                    dataObj["description"] = "data";
                required.Add("data");
                var schema = new global::System.Text.Json.Nodes.JsonObject
                {
                    ["type"] = "object",
                    ["properties"] = properties,
                };
                if (required.Count > 0)
                    schema["required"] = required;
                schema["additionalProperties"] = false;
                return global::System.Text.Json.JsonSerializer.SerializeToElement(schema);
            }

            private static global::System.Text.Json.JsonElement? BuildReturnSchema()
            {
                return null;
            }

            protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
                global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
                global::System.Threading.CancellationToken cancellationToken)
            {
                var __provider = arguments.Services ?? throw new global::System.InvalidOperationException(
                    "Tool 'dangerous_write' requires services (source type: global::Sample.IDangerousService) but no IServiceProvider was supplied. " +
                    "Set AIFunctionArguments.Services before invoking the tool (ChatClientBuilder.UseFunctionInvocation().Build(sp) does this automatically).");
                var __service = __provider.GetService<global::Sample.IDangerousService>() ?? throw new global::System.InvalidOperationException(
                    "Tool 'dangerous_write' could not resolve its source type 'global::Sample.IDangerousService' from IServiceProvider. " +
                    "Register the service in your DI container, or use ChatClientBuilder.UseFunctionInvocation().Build(sp) to supply a configured IServiceProvider.");
                var __arg_data = global::Microsoft.Maui.AI.Attributes.AIToolMetadataServices.GetRequiredArg<string>(arguments, "data", (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<string>)s_jsonOptions.GetTypeInfo(typeof(string)));
                __service.Write(__arg_data);
                return null;
            }
        }

    }
}
