//HintName: MauiAIAttributesGeneratorTestsToolContext.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS8019 // Unnecessary using directive
#pragma warning disable CS8604 // Possible null reference argument (JSON-deserialized values passed to non-nullable parameters)
#pragma warning disable CS1998 // Async method lacks 'await' operators (sync property getters/void tools are emitted as async)

using global::System;
using global::System.Collections.Generic;
using global::System.Text.Json;
using global::System.Threading;
using global::System.Threading.Tasks;
using global::Microsoft.Extensions.AI;
using global::Microsoft.Extensions.DependencyInjection;

namespace Sample
{
    internal partial class MauiAIAttributesGeneratorTestsToolContext : global::Microsoft.Maui.AI.Attributes.AIToolContext
    {
        /// <summary>Gets the default singleton instance of this tool context.</summary>
        public static MauiAIAttributesGeneratorTestsToolContext Default { get; } = new MauiAIAttributesGeneratorTestsToolContext();

        private static readonly global::System.Text.Json.JsonSerializerOptions s_jsonOptions = global::Microsoft.Extensions.AI.AIJsonUtilities.DefaultOptions;

        private static readonly global::Microsoft.Extensions.AI.AITool[] s_tools = new global::Microsoft.Extensions.AI.AITool[]
        {
            new Catalog_All_Get_Tool(),
        };

        /// <inheritdoc />
        public override global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Extensions.AI.AITool> Tools => s_tools;

        private sealed class Catalog_All_Get_Tool : global::Microsoft.Extensions.AI.AIFunction
        {
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);
            private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);

            public override string Name => "list_all";
            public override string Description => "Returns every item in the catalog.";
            public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;
            public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;

            private static global::System.Text.Json.JsonElement BuildSchema()
            {
                var properties = new global::System.Text.Json.Nodes.JsonObject();
                var required = new global::System.Text.Json.Nodes.JsonArray();
                var schema = new global::System.Text.Json.Nodes.JsonObject
                {
                    ["type"] = "object",
                    ["properties"] = properties,
                };
                if (required.Count > 0)
                    schema["required"] = required;
                schema["additionalProperties"] = false;
                return global::System.Text.Json.JsonSerializer.SerializeToElement(schema);
            }

            private static global::System.Text.Json.JsonElement? BuildReturnSchema()
            {
                return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof(global::System.Collections.Generic.IReadOnlyList<string>), serializerOptions: s_jsonOptions);
            }

            protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(
                global::Microsoft.Extensions.AI.AIFunctionArguments arguments,
                global::System.Threading.CancellationToken cancellationToken)
            {
                var __result = global::Sample.Catalog.All;
                return __result;
            }
        }

    }
}
