using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Microsoft.Maui.AI.Attributes.Generators;

internal static class CodeEmitter
{
    internal static string GenerateContextSource(ContextModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8019 // Unnecessary using directive");
        sb.AppendLine("#pragma warning disable CS8604 // Possible null reference argument (JSON-deserialized values passed to non-nullable parameters)");
        sb.AppendLine("#pragma warning disable CS1998 // Async method lacks 'await' operators (sync property getters/void tools are emitted as async)");
        sb.AppendLine();
        sb.AppendLine("using global::System;");
        sb.AppendLine("using global::System.Collections.Generic;");
        sb.AppendLine("using global::System.Text.Json;");
        sb.AppendLine("using global::System.Threading;");
        sb.AppendLine("using global::System.Threading.Tasks;");
        sb.AppendLine("using global::Microsoft.Extensions.AI;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        var indent = "";
        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        // Open containing type declarations (outermost first).
        foreach (var ct in model.ContainingTypes)
        {
            sb.AppendLine($"{indent}{ct.Accessibility} partial {ct.Keyword} {ct.Name}");
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }

        // Emit the partial class body: Default + Tools.
        var baseClause = model.EmitBaseClass ? " : global::Microsoft.Maui.AI.Attributes.AIToolContext" : "";
        sb.AppendLine($"{indent}{model.Accessibility} partial class {model.ClassName}{baseClause}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    /// <summary>Gets the default singleton instance of this tool context.</summary>");
        sb.AppendLine($"{indent}    public static {model.ClassName} Default {{ get; }} = new {model.ClassName}();");
        sb.AppendLine();

        // Static JsonSerializerOptions — use the M.E.AI default options which include a
        // pre-configured type info resolver. Schema creation and argument deserialization
        // both go through these options so behavior is consistent with ReflectionAIFunction.
        sb.AppendLine($"{indent}    private static readonly global::System.Text.Json.JsonSerializerOptions s_jsonOptions = global::Microsoft.Extensions.AI.AIJsonUtilities.DefaultOptions;");
        sb.AppendLine();

        // Tools property — cached in a static field so repeated access returns the same instance.
        sb.AppendLine($"{indent}    private static readonly global::Microsoft.Extensions.AI.AITool[] s_tools = new global::Microsoft.Extensions.AI.AITool[]");
        sb.AppendLine($"{indent}    {{");
        foreach (var st in model.SourceTypes)
        {
            foreach (var m in st.Methods)
            {
                sb.AppendLine($"{indent}        {WrapApproval($"new {m.GeneratedClassName}()", m.ApprovalRequired)},");
            }
        }
        sb.AppendLine($"{indent}    }};");
        sb.AppendLine();
        sb.AppendLine($"{indent}    /// <inheritdoc />");
        sb.AppendLine($"{indent}    public override global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Extensions.AI.AITool> Tools => s_tools;");

        // Emit tool classes as nested private classes inside the context class — avoids
        // cross-context name collisions when the same service method is referenced from
        // multiple [AIToolSource]-decorated contexts.
        sb.AppendLine();
        foreach (var st in model.SourceTypes)
        {
            foreach (var m in st.Methods)
            {
                EmitToolClass(sb, indent + "    ", st, m);
                sb.AppendLine();
            }
        }

        sb.AppendLine($"{indent}}}");

        // Close containing type declarations (innermost first).
        for (var i = model.ContainingTypes.Length - 1; i >= 0; i--)
        {
            indent = indent.Substring(4);
            sb.AppendLine($"{indent}}}");
        }

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string WrapApproval(string inner, bool approvalRequired) =>
        approvalRequired
            ? $"new global::Microsoft.Extensions.AI.ApprovalRequiredAIFunction({inner})"
            : inner;

    private static void EmitToolClass(StringBuilder sb, string indent, SourceTypeModel st, MethodModel m)
    {
        var cls = m.GeneratedClassName;

        // A tool requires a service provider when either:
        //   - the backing method is an instance method (we need to resolve the owning service), or
        //   - at least one parameter binds from DI (IServiceProvider / [FromServices] / [FromKeyedServices]).
        bool needsServiceForInstance = !m.IsStatic;
        bool anyParamNeedsServices = m.Parameters.Any(p =>
            p.Kind is ParameterKind.ServiceProvider
                  or ParameterKind.FromServices
                  or ParameterKind.FromKeyedServices);
        bool needsProvider = needsServiceForInstance || anyParamNeedsServices;

        sb.AppendLine($"{indent}private sealed class {cls} : global::Microsoft.Extensions.AI.AIFunction");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    private static readonly global::System.Lazy<global::System.Text.Json.JsonElement> s_schema = new(BuildSchema);");
        sb.AppendLine($"{indent}    private static readonly global::System.Lazy<global::System.Text.Json.JsonElement?> s_returnSchema = new(BuildReturnSchema);");
        sb.AppendLine();

        sb.AppendLine($"{indent}    public override string Name => {Escape(m.ToolName)};");
        sb.AppendLine($"{indent}    public override string Description => {EscapeOrEmpty(m.Description)};");
        sb.AppendLine($"{indent}    public override global::System.Text.Json.JsonElement JsonSchema => s_schema.Value;");
        sb.AppendLine($"{indent}    public override global::System.Text.Json.JsonElement? ReturnJsonSchema => s_returnSchema.Value;");
        sb.AppendLine();

        // Schema builder — uses the source-generated JsonSerializerOptions for AOT-safe schema creation.
        // Parameters excluded from the schema (DI-injected, CancellationToken, etc.) are listed here.
        var jsonParams = m.Parameters.Where(p => IncludeInSchema(p.Kind)).ToArray();

        sb.AppendLine($"{indent}    private static global::System.Text.Json.JsonElement BuildSchema()");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        var properties = new global::System.Text.Json.Nodes.JsonObject();");
        sb.AppendLine($"{indent}        var required = new global::System.Text.Json.Nodes.JsonArray();");
        foreach (var p in jsonParams)
        {
            sb.AppendLine($"{indent}        properties[{Escape(p.Name)}] = global::System.Text.Json.Nodes.JsonNode.Parse(global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof({p.UnannotatedTypeName}), serializerOptions: s_jsonOptions).GetRawText());");
            if (p.Description is not null)
            {
                sb.AppendLine($"{indent}        if (properties[{Escape(p.Name)}] is global::System.Text.Json.Nodes.JsonObject {SanitizeIdentifier(p.Name)}Obj)");
                sb.AppendLine($"{indent}            {SanitizeIdentifier(p.Name)}Obj[\"description\"] = {Escape(p.Description)};");
            }
            if (!p.HasDefault && !p.IsNullable)
            {
                sb.AppendLine($"{indent}        required.Add({Escape(p.Name)});");
            }
        }
        sb.AppendLine($"{indent}        var schema = new global::System.Text.Json.Nodes.JsonObject");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            [\"type\"] = \"object\",");
        sb.AppendLine($"{indent}            [\"properties\"] = properties,");
        sb.AppendLine($"{indent}        }};");
        sb.AppendLine($"{indent}        if (required.Count > 0)");
        sb.AppendLine($"{indent}            schema[\"required\"] = required;");
        sb.AppendLine($"{indent}        schema[\"additionalProperties\"] = false;");
        sb.AppendLine($"{indent}        return global::System.Text.Json.JsonSerializer.SerializeToElement(schema);");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        sb.AppendLine($"{indent}    private static global::System.Text.Json.JsonElement? BuildReturnSchema()");
        sb.AppendLine($"{indent}    {{");
        if (m.ReturnInfo.Shape == ReturnShape.Void || m.ReturnInfo.Shape == ReturnShape.Task || m.ReturnInfo.Shape == ReturnShape.ValueTask)
        {
            sb.AppendLine($"{indent}        return null;");
        }
        else
        {
            sb.AppendLine($"{indent}        return global::Microsoft.Extensions.AI.AIJsonUtilities.CreateJsonSchema(typeof({m.ReturnInfo.TypeName!}), serializerOptions: s_jsonOptions);");
        }
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        // InvokeCoreAsync
        sb.AppendLine($"{indent}    protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(");
        sb.AppendLine($"{indent}        global::Microsoft.Extensions.AI.AIFunctionArguments arguments,");
        sb.AppendLine($"{indent}        global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine($"{indent}    {{");

        if (needsProvider)
        {
            sb.AppendLine($"{indent}        var __provider = arguments.Services ?? throw new global::System.InvalidOperationException(");
            sb.AppendLine($"{indent}            \"Tool '{m.ToolName}' requires services (source type: {st.FullyQualifiedName}) but no IServiceProvider was supplied. \" +");
            sb.AppendLine($"{indent}            \"Set AIFunctionArguments.Services before invoking the tool (ChatClientBuilder.UseFunctionInvocation().Build(sp) does this automatically).\");");
        }
        if (needsServiceForInstance)
        {
            sb.AppendLine($"{indent}        var __service = __provider.GetService<{st.FullyQualifiedName}>() ?? throw new global::System.InvalidOperationException(");
            sb.AppendLine($"{indent}            \"Tool '{m.ToolName}' could not resolve its source type '{st.FullyQualifiedName}' from IServiceProvider. \" +");
            sb.AppendLine($"{indent}            \"Register the service in your DI container, or use ChatClientBuilder.UseFunctionInvocation().Build(sp) to supply a configured IServiceProvider.\");");
        }

        var argNames = new List<string>();
        foreach (var p in m.Parameters)
        {
            var local = $"__arg_{p.Name}";
            argNames.Add(local);
            EmitParameterBinding(sb, indent + "        ", local, p);
        }

        // Call & await — static members call via the type; instance members go through __service.
        var receiver = m.IsStatic ? st.FullyQualifiedName : "__service";
        var callExpr = m.IsProperty
            ? (m.IsPropertySetter
                ? $"({receiver}.{m.MethodName} = {argNames.Single()})"
                : $"{receiver}.{m.MethodName}")
            : $"{receiver}.{m.MethodName}({string.Join(", ", argNames)})";
        switch (m.ReturnInfo.Shape)
        {
            case ReturnShape.Void:
                sb.AppendLine($"{indent}        {callExpr};");
                sb.AppendLine($"{indent}        return null;");
                break;
            case ReturnShape.Sync:
                sb.AppendLine($"{indent}        var __result = {callExpr};");
                sb.AppendLine($"{indent}        return __result;");
                break;
            case ReturnShape.Task:
                sb.AppendLine($"{indent}        await {callExpr}.ConfigureAwait(false);");
                sb.AppendLine($"{indent}        return null;");
                break;
            case ReturnShape.ValueTask:
                sb.AppendLine($"{indent}        await {callExpr}.ConfigureAwait(false);");
                sb.AppendLine($"{indent}        return null;");
                break;
            case ReturnShape.TaskOfT:
            case ReturnShape.ValueTaskOfT:
                sb.AppendLine($"{indent}        var __result = await {callExpr}.ConfigureAwait(false);");
                sb.AppendLine($"{indent}        return __result;");
                break;
        }

        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");
    }

    private static void EmitParameterBinding(StringBuilder sb, string indent, string local, ParameterModel p)
    {
        switch (p.Kind)
        {
            case ParameterKind.CancellationToken:
                sb.AppendLine($"{indent}var {local} = cancellationToken;");
                break;
            case ParameterKind.ServiceProvider:
                sb.AppendLine($"{indent}var {local} = __provider;");
                break;
            case ParameterKind.AIFunctionArguments:
                sb.AppendLine($"{indent}var {local} = arguments;");
                break;
            case ParameterKind.FromServices:
                sb.AppendLine($"{indent}var {local} = __provider.GetService<{p.TypeName}>() ?? throw new global::System.InvalidOperationException(");
                sb.AppendLine($"{indent}    \"Tool parameter '{p.Name}' of type '{p.TypeName}' could not be resolved from IServiceProvider. \" +");
                sb.AppendLine($"{indent}    \"Register the service in your DI container.\");");
                break;
            case ParameterKind.FromKeyedServices:
                var keyLiteral = p.KeyedServiceKey ?? "null";
                // Use (as IKeyedServiceProvider)?. pattern because the extension method GetKeyedService
                // throws InvalidOperationException("KeyedServicesNotSupported") when the provider doesn't
                // implement IKeyedServiceProvider (e.g. EmptyServiceProvider). By going through the
                // interface directly, non-keyed providers yield null which our ?? throw catches with a
                // contextual error message.
                sb.AppendLine($"{indent}var {local} = ({p.TypeName}?)(__provider as global::Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider)?.GetKeyedService(typeof({p.TypeName}), {keyLiteral})");
                sb.AppendLine($"{indent}    ?? throw new global::System.InvalidOperationException(");
                sb.AppendLine($"{indent}        \"Tool parameter '{p.Name}' of type '{p.TypeName}' could not be resolved from IServiceProvider with key \" + {keyLiteral} + \". \" +");
                sb.AppendLine($"{indent}        \"Register the keyed service in your DI container, or ensure the IServiceProvider supports keyed services (IKeyedServiceProvider).\");");
                break;
            case ParameterKind.JsonArgument:
                var typeInfoExpr = $"(global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{p.TypeName}>)s_jsonOptions.GetTypeInfo(typeof({p.UnannotatedTypeName}))";
                if (p.HasDefault)
                {
                    sb.AppendLine($"{indent}var {local} = global::Microsoft.Maui.AI.Attributes.AIToolMetadataServices.GetOptionalArg<{p.TypeName}>(arguments, {Escape(p.Name)}, {p.DefaultLiteral}, {typeInfoExpr});");
                }
                else
                {
                    sb.AppendLine($"{indent}var {local} = global::Microsoft.Maui.AI.Attributes.AIToolMetadataServices.GetRequiredArg<{p.TypeName}>(arguments, {Escape(p.Name)}, {typeInfoExpr});");
                }
                break;
            default:
                sb.AppendLine($"{indent}// Unclassified parameter {p.Name}: falling back to JSON binding.");
                var fallbackTypeInfo = $"(global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{p.TypeName}>)s_jsonOptions.GetTypeInfo(typeof({p.UnannotatedTypeName}))";
                sb.AppendLine($"{indent}var {local} = global::Microsoft.Maui.AI.Attributes.AIToolMetadataServices.GetRequiredArg<{p.TypeName}>(arguments, {Escape(p.Name)}, {fallbackTypeInfo});");
                break;
        }
    }

    private static bool IncludeInSchema(ParameterKind kind) =>
        kind is ParameterKind.JsonArgument;

    internal static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
        {
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }
        return sb.ToString();
    }

    internal static string Escape(string value)
        => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);

    internal static string EscapeOrNull(string? value)
        => value is null ? "null" : Escape(value);

    internal static string EscapeOrEmpty(string? value)
        => value is null ? "string.Empty" : Escape(value);
}
